In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder

In [4]:
df= pd.read_csv("C:/Users/Santhoshkumar S/Desktop/Datascience/file.csv/file.csv")
df.head()

,Unnamed: 0,CustomerID,Gender,Location,Tenure_Months,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,...,Avg_Price,Delivery_Charges,Coupon_Status,GST,Date,Offline_Spend,Online_Spend,Month,Coupon_Code,Discount_pct
0,0,17850.0,M,Chicago,12.0,16679.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,153.71,6.5,Used,0.1,1/1/2019,4500.0,2424.5,1,ELEC10,10.0
1,1,17850.0,M,Chicago,12.0,16680.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,153.71,6.5,Used,0.1,1/1/2019,4500.0,2424.5,1,ELEC10,10.0
2,2,17850.0,M,Chicago,12.0,16696.0,2019-01-01,GGOENEBQ078999,Nest Cam Outdoor Security Camera - USA,Nest-USA,...,122.77,6.5,Not Used,0.1,1/1/2019,4500.0,2424.5,1,ELEC10,10.0
3,3,17850.0,M,Chicago,12.0,16699.0,2019-01-01,GGOENEBQ079099,Nest Protect Smoke + CO White Battery Alarm-USA,Nest-USA,...,81.50,6.5,Clicked,0.1,1/1/2019,4500.0,2424.5,1,ELEC10,10.0
4,4,17850.0,M,Chicago,12.0,16700.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,153.71,6.5,Clicked,0.1,1/1/2019,4500.0,2424.5,1,ELEC10,10.0

In [5]:
print(df.tail())

       Unnamed: 0  CustomerID Gender Location  Tenure_Months  Transaction_ID  \
52950       52950         NaN    NaN      NaN            NaN             NaN
52951       52951         NaN    NaN      NaN            NaN             NaN
52952       52952         NaN    NaN      NaN            NaN             NaN
52953       52953         NaN    NaN      NaN            NaN             NaN
52954       52954         NaN    NaN      NaN            NaN             NaN

      Transaction_Date Product_SKU Product_Description      Product_Category  \
52950              NaN         NaN                 NaN            Gift Cards
52951              NaN         NaN                 NaN  Notebooks & Journals
52952              NaN         NaN                 NaN               Android
52953              NaN         NaN                 NaN               Android
52954              NaN         NaN                 NaN               Android

       ...  Avg_Price  Delivery_Charges  Coupon_Status GST  Date  \
52950  ...        NaN               NaN            NaN NaN   NaN
52951  ...        NaN               NaN            NaN NaN   NaN
52952  ...        NaN               NaN            NaN NaN   NaN
52953  ...        NaN               NaN            NaN NaN   NaN
52954  ...        NaN               NaN            NaN NaN   NaN

      Offline_Spend  Online_Spend  Month  Coupon_Code Discount_pct
52950           NaN           NaN     11         GC20         20.0
52951           NaN           NaN     11         NJ20         20.0
52952           NaN           NaN     10        AND10         10.0
52953           NaN           NaN     11        AND20         20.0
52954           NaN           NaN     12        AND30         30.0

[5 rows x 21 columns]

In [4]:
print(df.size)

1112055

In [5]:
print(df.shape)

(52955, 21)

In [6]:
print(df.columns)

Index(['Unnamed: 0', 'CustomerID', 'Gender', 'Location', 'Tenure_Months',
       'Transaction_ID', 'Transaction_Date', 'Product_SKU',
       'Product_Description', 'Product_Category', 'Quantity', 'Avg_Price',
       'Delivery_Charges', 'Coupon_Status', 'GST', 'Date', 'Offline_Spend',
       'Online_Spend', 'Month', 'Coupon_Code', 'Discount_pct'],
      dtype='str')

In [7]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 52955 entries, 0 to 52954
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           52955 non-null  int64
 1   CustomerID           52924 non-null  float64
 2   Gender               52924 non-null  str
 3   Location             52924 non-null  str
 4   Tenure_Months        52924 non-null  float64
 5   Transaction_ID       52924 non-null  float64
 6   Transaction_Date     52924 non-null  str
 7   Product_SKU          52924 non-null  str
 8   Product_Description  52924 non-null  str
 9   Product_Category     52955 non-null  str
 10  Quantity             52924 non-null  float64
 11  Avg_Price            52924 non-null  float64
 12  Delivery_Charges     52924 non-null  float64
 13  Coupon_Status        52924 non-null  str
 14  GST                  52924 non-null  float64
 15  Date                 52924 non-null  str
 16  Offline_Spend        52924 non-null  float64
 17  Online_Spend         52924 non-null  float64
 18  Month                52955 non-null  int64
 19  Coupon_Code          52555 non-null  str
 20  Discount_pct         52555 non-null  float64
dtypes: float64(10), int64(2), str(9)
memory usage: 8.5 MB
None

In [8]:
print(df.dtypes)

Unnamed: 0               int64
CustomerID             float64
Gender                     str
Location                   str
Tenure_Months          float64
Transaction_ID         float64
Transaction_Date           str
Product_SKU                str
Product_Description        str
Product_Category           str
Quantity               float64
Avg_Price              float64
Delivery_Charges       float64
Coupon_Status              str
GST                    float64
Date                       str
Offline_Spend          float64
Online_Spend           float64
Month                    int64
Coupon_Code                str
Discount_pct           float64
dtype: object

In [9]:
df.fillna(df.mode().iloc[0], inplace=True)

,Unnamed: 0,CustomerID,Gender,Location,Tenure_Months,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,...,Avg_Price,Delivery_Charges,Coupon_Status,GST,Date,Offline_Spend,Online_Spend,Month,Coupon_Code,Discount_pct
0,0,17850.0,M,Chicago,12.0,16679.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,153.71,6.5,Used,0.10,1/1/2019,4500.0,2424.50,1,ELEC10,10.0
1,1,17850.0,M,Chicago,12.0,16680.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,153.71,6.5,Used,0.10,1/1/2019,4500.0,2424.50,1,ELEC10,10.0
2,2,17850.0,M,Chicago,12.0,16696.0,2019-01-01,GGOENEBQ078999,Nest Cam Outdoor Security Camera - USA,Nest-USA,...,122.77,6.5,Not Used,0.10,1/1/2019,4500.0,2424.50,1,ELEC10,10.0
3,3,17850.0,M,Chicago,12.0,16699.0,2019-01-01,GGOENEBQ079099,Nest Protect Smoke + CO White Battery Alarm-USA,Nest-USA,...,81.50,6.5,Clicked,0.10,1/1/2019,4500.0,2424.50,1,ELEC10,10.0
4,4,17850.0,M,Chicago,12.0,16700.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,153.71,6.5,Clicked,0.10,1/1/2019,4500.0,2424.50,1,ELEC10,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52950,52950,12748.0,F,Chicago,40.0,32526.0,2019-11-27,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Gift Cards,...,119.00,6.0,Clicked,0.18,11/27/2019,3000.0,2819.58,11,GC20,20.0
52951,52951,12748.0,F,Chicago,40.0,32526.0,2019-11-27,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Notebooks & Journals,...,119.00,6.0,Clicked,0.18,11/27/2019,3000.0,2819.58,11,NJ20,20.0
52952,52952,12748.0,F,Chicago,40.0,32526.0,2019-11-27,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Android,...,119.00,6.0,Clicked,0.18,11/27/2019,3000.0,2819.58,10,AND10,10.0
52953,52953,12748.0,F,Chicago,40.0,32526.0,2019-11-27,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Android,...,119.00,6.0,Clicked,0.18,11/27/2019,3000.0,2819.58,11,AND20,20.0
52954,52954,12748.0,F,Chicago,40.0,32526.0,2019-11-27,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Android,...,119.00,6.0,Clicked,0.18,11/27/2019,3000.0,2819.58,12,AND30,30.0

In [10]:
df.drop_duplicates(inplace=True)

In [11]:
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

In [13]:
print(df.loc[0:4, ['Gender', 'Location']])
print(df.iloc[0:5, 0:3])

  Gender Location
0      M  Chicago
1      M  Chicago
2      M  Chicago
3      M  Chicago
4      M  Chicago
   Unnamed: 0  CustomerID Gender
0           0     17850.0      M
1           1     17850.0      M
2           2     17850.0      M
3           3     17850.0      M
4           4     17850.0      M

In [6]:
print(df[df['Gender'] == 'Male'])

Empty DataFrame
Columns: [Unnamed: 0, CustomerID, Gender, Location, Tenure_Months, Transaction_ID, Transaction_Date, Product_SKU, Product_Description, Product_Category, Quantity, Avg_Price, Delivery_Charges, Coupon_Status, GST, Date, Offline_Spend, Online_Spend, Month, Coupon_Code, Discount_pct]
Index: []

[0 rows x 21 columns]

In [9]:
print(df.columns.tolist())

['Unnamed: 0', 'CustomerID', 'Gender', 'Location', 'Tenure_Months', 'Transaction_ID', 'Transaction_Date', 'Product_SKU', 'Product_Description', 'Product_Category', 'Quantity', 'Avg_Price', 'Delivery_Charges', 'Coupon_Status', 'GST', 'Date', 'Offline_Spend', 'Online_Spend', 'Month', 'Coupon_Code', 'Discount_pct']

In [10]:
print(df.head())

   Unnamed: 0  CustomerID Gender Location  Tenure_Months  Transaction_ID  \
0           0     17850.0      M  Chicago           12.0         16679.0
1           1     17850.0      M  Chicago           12.0         16680.0
2           2     17850.0      M  Chicago           12.0         16696.0
3           3     17850.0      M  Chicago           12.0         16699.0
4           4     17850.0      M  Chicago           12.0         16700.0

  Transaction_Date     Product_SKU  \
0       2019-01-01  GGOENEBJ079499
1       2019-01-01  GGOENEBJ079499
2       2019-01-01  GGOENEBQ078999
3       2019-01-01  GGOENEBQ079099
4       2019-01-01  GGOENEBJ079499

                                 Product_Description Product_Category  ...  \
0  Nest Learning Thermostat 3rd Gen-USA - Stainle...         Nest-USA  ...
1  Nest Learning Thermostat 3rd Gen-USA - Stainle...         Nest-USA  ...
2             Nest Cam Outdoor Security Camera - USA         Nest-USA  ...
3    Nest Protect Smoke + CO White Battery Alarm-USA         Nest-USA  ...
4  Nest Learning Thermostat 3rd Gen-USA - Stainle...         Nest-USA  ...

   Avg_Price  Delivery_Charges  Coupon_Status  GST      Date Offline_Spend  \
0     153.71               6.5           Used  0.1  1/1/2019        4500.0
1     153.71               6.5           Used  0.1  1/1/2019        4500.0
2     122.77               6.5       Not Used  0.1  1/1/2019        4500.0
3      81.50               6.5        Clicked  0.1  1/1/2019        4500.0
4     153.71               6.5        Clicked  0.1  1/1/2019        4500.0

   Online_Spend  Month  Coupon_Code Discount_pct
0        2424.5      1       ELEC10         10.0
1        2424.5      1       ELEC10         10.0
2        2424.5      1       ELEC10         10.0
3        2424.5      1       ELEC10         10.0
4        2424.5      1       ELEC10         10.0

[5 rows x 21 columns]

In [11]:
df['New_Age'] = df['Age'] + 5

KeyError: 'Age'